# Generated by Django 4.2.3 on 2024-10-07 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('STROOP1', 'stroop1'), ('STROOP2', 'stroop2'), ('STROOP3', 'stroop3'), ('STROOP4', 'stroop4'), ('ARITHM', 'arithm'), ('VISUAL', 'visual'), ('VISUAL_COLOR', 'visual_color'), ('VISUAL_PLUS_COLOR', 'visual_plus_color'), ('MEMORY', 'memory'), ('MUNSTER', 'munster'), ('RAVEN', 'raven')], max_length=255)),
                ('answers_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.answers')),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('is_timed', models.BooleanField(default=False)),
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=255)),
                ('answers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.answers')),
                ('questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.questions')),
                ('test_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.testsession')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='results_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.results'),
        ),
        migrations.AddField(
            model_name='questions',
            name='test_session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.testsession'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_num', models.IntegerField()),
                ('question_desc', models.CharField(max_length=255)),
                ('questions_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.questions')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='questions_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='results_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.results'),
        ),
        migrations.AddField(
            model_name='answers',
            name='test_session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.testsession'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_num', models.IntegerField()),
                ('answer_type', models.CharField(choices=[('CHOICE', 'choice'), ('NUM', 'num'), ('WORDS', 'words')], max_length=255)),
                ('answer_options', models.CharField(max_length=255, null=True)),
                ('right_answer', models.CharField(max_length=255)),
                ('given_answer', models.CharField(max_length=255)),
                ('answers_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.answers')),
            ],
        ),
    ]
