# Generated by Django 4.2.3 on 2024-10-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='given_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='test_type',
            field=models.CharField(choices=[('STROOP1', 'stroop1'), ('STROOP2', 'stroop2'), ('STROOP3', 'stroop3'), ('STROOP4', 'stroop4'), ('ARITHM', 'arithm'), ('VISUAL', 'visual'), ('VISUAL_COLOR', 'visual_color'), ('VISUAL_PLUS_COLOR', 'visual_plus_color'), ('MEMORY', 'memory')], max_length=255),
        ),
    ]
