# Generated by Django 4.2.3 on 2024-11-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_answer_given_answer_alter_questions_test_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer_id',
            new_name='answers_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_id',
            new_name='question_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_options',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answers_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='results_id',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='is_timed',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('CHOICE', 0), ('WORDS', 1)], max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='test_type',
            field=models.CharField(choices=[('STROOP1', 'stroop1'), ('STROOP2', 'stroop2'), ('STROOP3', 'stroop3'), ('STROOP4', 'stroop4'), ('ARITHM', 'arithm'), ('SPATIAL', 'spatial'), ('SHAPES', 'shapes'), ('COLOR', 'color'), ('SPATIAL', 'spatial'), ('SHAPES_COLOR', 'shapes_color'), ('SHAPES_SPATIAL', 'shapes_spatial'), ('MEMORY', 'memory'), ('MUNSTER', 'munster'), ('RAVEN', 'raven')], max_length=255),
        ),
    ]
