# Generated by Django 4.2.3 on 2024-11-18 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_answers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='user_id',
            field=models.ForeignKey(default=quiz_app.models.Profile, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
