# Generated by Django 4.2.3 on 2024-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_answers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='test_type',
            field=models.CharField(choices=[('STROOP2', 'stroop2'), ('STROOP3', 'stroop3'), ('STROOP4', 'stroop4'), ('ARITHM', 'arithm'), ('SPATIAL', 'spatial'), ('SHAPES', 'shapes'), ('SHAPES_COLOR', 'shapes_color'), ('SHAPES_SPATIAL', 'shapes_spatial'), ('MEMORY', 'memory'), ('MUNSTER', 'munster'), ('RAVEN', 'raven')], max_length=255),
        ),
    ]
